const marc21 = {
  tags: {
    '100': 'Heading - Personal Name (NR)',
    '101': 'unassigned',
    '109': 'unassigned',
    '110': 'Heading - Corporate Name (NR)',
    '111': 'Heading - Meeting Name (NR)',
    '112': 'unassigned',
    '129': 'unassigned',
    '130': 'Heading - Uniform Title (NR)',
    '131': 'unassigned',
    '139': 'unassigned',
    '140': 'Uniform Title',
    '141': 'unassigned',
    '142': 'unassigned',
    '143': 'Collective Title',
    '144': 'unassigned',
    '146': 'unassigned',
    '147': 'Heading - Named Event (NR)',
    '148': 'Heading - Chronological Term (NR)',
    '149': 'unassigned',
    '150': 'Heading - Topical Term (NR)',
    '151': 'Heading - Geographic Name (NR)',
    '152': 'unassigned',
    '154': 'unassigned',
    '155': 'Heading - Genre/Form Term (NR)',
    '156': 'unassigned',
    '161': 'unassigned',
    '162': 'Heading - Medium of Performance Term (NR)',
    '163': 'unassigned',
    '179': 'unassigned',
    '180': 'Heading - General Subdivision (NR)',
    '181': 'Heading - Geographic Subdivision (NR)',
    '182': 'Heading - Chronological Subdivision (NR)',
    '183': 'unassigned',
    '184': 'unassigned',
    '185': ' Heading - Form Subdivision (NR)',
    '186': 'unassigned',
    '199': 'unassigned',
    '200': 'unassigned',
    '259': 'unassigned',
    '260': 'Complex See Reference - Subject (R)',
    '261': 'unassigned',
    '299': 'unassigned',
    '300': 'unassigned',
    '335': 'unassigned',
    '336': 'Content Type  (R)',
    '337': 'unassigned',
    '347': 'unassigned',
    '348': 'Format of Notated Music (R)',
    '349': 'unassigned',
    '359': 'unassigned',
    '360': 'Complex See Also Reference - Subject (R)',
    '361': 'unassigned',
    '367': 'unassigned',
    '368': 'Other Attributes of Person or Corporate Body (R)',
    '369': 'unassigned',
    '370': 'Associated Place (R)',
    '371': 'Address  (R)',
    '372': 'Field of Activity (R)',
    '373': 'Associated Group (R)',
    '374': 'Occupation (R)',
    '375': 'Gender (R)',
    '376': 'Family Information (R)',
    '377': 'Associated Language (R)',
    '378': 'Fuller Form of Personal Name (NR)',
    '379': 'unassigned',
    '380': 'Form of Work (R)',
    '381': 'Other Distinguishing Characteristics of Work or Expression (R)',
    '382': ' Medium of Performance (R)',
    '383': 'Numeric Designation of Musical Work (R)',
    '384': 'Key (NR)',
    '385': 'Audience Characteristics (R)',
    '386': 'Creator/Contributor Characteristics (R)',
    '387': 'unassigned',
    '388': 'Time Period of Creation (R)',
    '389': 'unassigned',
    '399': 'unassigned',
    '400': 'See From Tracing - Personal Name (R)',
    '401': 'unassigned',
    '409': 'unassigned',
    '410': 'See From Tracing - Corporate Name (R)',
    '411': 'See From Tracing - Meeting Name (R)',
    '412': 'unassigned',
    '429': 'unassigned',
    '430': 'See From Tracing - Uniform Title (R)',
    '431': 'unassigned',
    '446': 'unassigned',
    '447': 'See From Tracing - Named Event (R)',
    '448': 'See From Tracing - Chronological Term (R)',
    '449': 'unassigned',
    '450': 'See From Tracing - Topical Term (R)',
    '451': 'See From Tracing - Geographic Name (R)',
    '452': 'unassigned',
    '454': 'unassigned',
    '455': 'See From Tracing - Genre/Form Term (R)',
    '456': 'unassigned',
    '461': 'unassigned',
    '462': 'See From Tracing - Medium of Performance Term (R)',
    '463': 'unassigned',
    '479': 'unassigned',
    '480': 'See From Tracing - General Subdivision (R)',
    '481': 'See From Tracing - Geographic Subdivision (R)',
    '482': 'See From Tracing - Chronological Subdivision (R)',
    '483': 'unassigned',
    '484': 'unassigned',
    '485': 'See From Tracing - Form Subdivision (R)',
    '486': 'unassigned',
    '499': 'unassigned',
    '500': 'See Also From Tracing - Personal Name (R)',
    '501': 'unassigned',
    '509': 'unassigned',
    '510': ' See Also From Tracing - Corporate Name (R)',
    '511': ' See Also From Tracing - Meeting Name (R)',
    '512': 'unassigned',
    '529': 'unassigned',
    '530': 'See Also From Tracing - Uniform Title (R)',
    '531': 'unassigned',
    '546': 'unassigned',
    '547': 'See Also From Tracing - Named Event (R)',
    '548': ' See Also From Tracing - Chronological Term (R)',
    '549': 'unassigned',
    '550': ' See Also From Tracing - Topical Term (R)',
    '551': 'See Also From Tracing - Geographic Name (R)',
    '552': 'unassigned',
    '554': 'unassigned',
    '555': 'See Also From Tracing - Genre/Form Term (R)',
    '556': 'unassigned',
    '561': 'unassigned',
    '562': 'See Also From Tracing - Medium of Performance Term (R)',
    '563': 'unassigned',
    '579': 'unassigned',
    '580': 'See Also From Tracing - General Subdivision (R)',
    '581': 'See Also From Tracing - Geographic Subdivision (R)',
    '582': 'See Also From Tracing - Chronological Subdivision (R)',
    '583': 'unassigned',
    '584': 'unassigned',
    '585': 'See Also From Tracing - Form Subdivision (R)',
    '586': 'unassigned',
    '599': 'unassigned',
    '600': 'unassigned',
    '639': 'unassigned',
    '640': 'Series Dates of Publication and/or Sequential Designation (R)',
    '641': 'Series Numbering Peculiarities (R)',
    '642': 'Series Numbering Example (R)',
    '643': 'Series Place and Publisher/Issuing Body (R)',
    '644': 'Series Analysis Practice (R)',
    '645': 'Series Tracing Practice (R)',
    '646': 'Series Classification Practice (R)',
    '647': 'unassigned',
    '649': 'unassigned',
    '650': 'unassigned',
    '662': 'unassigned',
    '663': 'Complex See Also Reference - Name (NR)',
    '664': 'Complex See Reference - Name (NR)',
    '665': 'History Reference (NR)',
    '666': 'General Explanatory Reference - Name (NR)',
    '667': 'Nonpublic General Note (R)',
    '668': 'Note - Characters in Nonroman Alphabets',
    '669': 'unassigned',
    '670': 'Source Data Found (R)',
    '671': 'Note - Work Catalogued (Names/Titles)',
    '672': 'Title Related to the Entity (R)',
    '673': 'Title Not Related to the Entity (R)',
    '674': 'unassigned',
    '675': 'Source Data Not Found (NR)',
    '676': 'Note - Cataloging Rules (Names/Titles)',
    '677': 'Definition  (R)',
    '678': 'Biographical or Historical Data (R)',
    '679': 'unassigned',
    '680': 'Public General Note (R)',
    '681': 'Subject Example Tracing Note (R)',
    '682': 'Deleted Heading Information (NR)',
    '683': 'unassigned',
    '684': 'unassigned',
    '685': 'Note - Source Data Found (Subjects)',
    '686': 'Note - Source Data Not Found (Subjects)',
    '687': 'Note - Usage (Subjects)',
    '688': 'Application History Note (R)',
    '689': 'unassigned',
    '699': 'unassigned',
    '700': 'Established Heading Linking Entry - Personal Name (R)',
    '701': 'unassigned',
    '709': 'unassigned',
    '710': 'Established Heading Linking Entry - Corporate Name (R)',
    '711': 'Established Heading Linking Entry - Meeting Name (R)',
    '712': 'unassigned',
    '729': 'unassigned',
    '730': 'Established Heading Linking Entry - Uniform Title (R)',
    '731': 'unassigned',
    '746': 'unassigned',
    '747': 'Established Heading Linking Entry - Named Event (R)',
    '748': 'Established Heading Linking Entry - Chronological Term (R)',
    '749': 'unassigned',
    '750': 'Established Heading Linking Entry - Topical Term (R)',
    '751': 'Established Heading Linking Entry - Geographic Name (R)',
    '752': 'unassigned',
    '754': 'unassigned',
    '755': 'Established Heading Linking Entry - Genre/Form Term (R)',
    '756': 'unassigned',
    '761': 'unassigned',
    '762': 'Established Heading Linking Entry - Medium of Performance Term (R)',
    '763': 'unassigned',
    '779': 'unassigned',
    '780': 'Subdivision Linking Entry - General Subdivision (R)',
    '781': 'Subdivision Linking Entry - Geographic Subdivision (R)',
    '782': 'Subdivision Linking Entry - Chronological Subdivision (R)',
    '783': 'unassigned',
    '784': 'unassigned',
    '785': 'Subdivision Linking Entry - Form Subdivision (R)',
    '786': 'unassigned',
    '787': 'unassigned',
    '788': 'Complex Linking Entry Data (NR)',
    '789': 'unassigned',
    '799': 'unassigned',
    '800': 'unassigned',
    '855': 'unassigned',
    '856': 'Electronic Location and Access (R)',
    '857': 'unassigned',
    '879': 'unassigned',
    '880': 'Alternate Graphic Representation (R)',
    '881': 'unassigned',
    '882': 'unassigned',
    '883': 'Machine-generated Metadata Provenance (R)',
    '884': 'Description Conversion Information (R)',
    '885': 'Matching Information (R)',
    '886': 'unassigned',
    '899': 'unassigned',
    '001': 'Control Number  (NR)',
    '002': 'unassigned',
    '003': 'Control Number Identifier  (NR)',
    '004': 'unassigned',
    '005': 'Date and Time of Latest Transaction  (NR)',
    '006': 'unassigned',
    '007': 'unassigned',
    '008': 'Fixed-Length Data Elements  (NR)',
    '009': 'unassigned',
    '010': 'Library of Congress Control Number  (NR)',
    '011': 'unassigned',
    '013': 'unassigned',
    '014': 'Link to Bibliographic Record for Serial or Multipart Item (R)',
    '015': 'unassigned',
    '016': 'National Bibliographic Agency Control Number (R)',
    '017': 'unassigned',
    '019': 'unassigned',
    '020': 'International Standard Book Number (R)',
    '021': 'unassigned',
    '022': 'International Standard Serial Number (R)',
    '023': 'unassigned',
    '024': 'Other Standard Identifier (R)',
    '025': 'unassigned',
    '030': 'unassigned',
    '031': 'Musical Incipits Information (R)',
    '032': 'unassigned',
    '033': 'unassigned',
    '034': 'Coded Cartographic Mathematical Data (R)',
    '035': 'System Control Number (R)',
    '036': 'unassigned',
    '039': 'unassigned',
    '040': 'Cataloging Source (NR)',
    '041': 'unassigned',
    '042': 'Authentication Code (NR)',
    '043': 'Geographic Area Code (NR)',
    '044': 'unassigned',
    '045': 'Time Period of Heading (NR)',
    '046': 'Special Coded Dates (R)',
    '047': 'unassigned',
    '049': 'unassigned',
    '050': 'Library of Congress Call Number (R)',
    '051': 'unassigned',
    '052': 'Geographic Classification (R)',
    '053': 'LC Classification Number (R)',
    '054': 'unassigned',
    '055': 'Library and Archives Canada Call Number (R)',
    '056': 'unassigned',
    '057': 'unassigned',
    '058': 'LC Classification Number Assigned in Canada]',
    '059': 'unassigned',
    '060': 'National Library of Medicine Call Number (R)',
    '061': 'unassigned',
    '062': 'unassigned',
    '063': 'NLM Classification Number Assigned by NLM',
    '064': 'unassigned',
    '065': 'Other Classification Number (R)',
    '066': 'Character Sets Present (NR)',
    '067': 'unassigned',
    '068': 'NLM Classification Number Assigned in Canada',
    '069': 'unassigned',
    '9XX': 'Equivalent Headings',
    '070': 'National Agricultural Library Call Number (R)',
    '071': 'unassigned',
    '072': 'Subject Category Code (R)',
    '073': 'Subdivision Usage (NR)',
    '074': 'unassigned',
    '075': ' Type of Entity (R)',
    '076': 'unassigned',
    '079': 'unassigned',
    '080': 'Universal Decimal Classification Number (R)',
    '081': 'unassigned',
    '082': 'Dewey Decimal Call Number (R)',
    '083': ' Dewey Decimal Classification Number (R)',
    '084': 'unassigned',
    '085': 'unassigned',
    '086': 'Government Document Call Number (R)',
    '087': 'Government Document Classification Number (R)',
    '088': 'Document Shelving Number (CODOC)',
    '089': 'unassigned',
    '09X': 'Local Call Numbers'
  }
};

export default marc21;
