module.exports = [
  { 'label': 'Select Language', 'value': '' },
  { 'label': 'Abkhaz', 'value': 'аҧсуа' },
  { 'label': 'Afar', 'value': 'Afaraf' },
  { 'label': 'Afrikaans', 'value': 'Afrikaans' },
  { 'label': 'Akan', 'value': 'Akan' },
  { 'label': 'Albanian', 'value': 'Shqip' },
  { 'label': 'Amharic', 'value': 'አማርኛ' },
  { 'label': 'Arabic', 'value': 'العربية' },
  { 'label': 'Aragonese', 'value': 'Aragonés' },
  { 'label': 'Armenian', 'value': 'Հայերեն' },
  { 'label': 'Assamese', 'value': 'অসমীয়া' },
  { 'label': 'Avaric', 'value': 'авар мацӀ, магӀарул мацӀ' },
  { 'label': 'Avestan', 'value': 'avesta' },
  { 'label': 'Aymara', 'value': 'aymar aru' },
  { 'label': 'Azerbaijani', 'value': 'azərbaycan dili' },
  { 'label': 'Bambara', 'value': 'bamanankan' },
  { 'label': 'Bashkir', 'value': 'башҡорт теле' },
  { 'label': 'Basque', 'value': 'euskara, euskera' },
  { 'label': 'Belarusian', 'value': 'Беларуская' },
  { 'label': 'Bengali', 'value': 'বাংলা' },
  { 'label': 'Bihari', 'value': 'भोजपुरी' },
  { 'label': 'Bislama', 'value': 'Bislama' },
  { 'label': 'Bosnian', 'value': 'bosanski jezik' },
  { 'label': 'Breton', 'value': 'brezhoneg' },
  { 'label': 'Bulgarian', 'value': 'български език' },
  { 'label': 'Burmese', 'value': 'ဗမာစာ' },
  { 'label': 'Catalan; Valencian', 'value': 'Català' },
  { 'label': 'Chamorro', 'value': 'Chamoru' },
  { 'label': 'Chechen', 'value': 'нохчийн мотт' },
  { 'label': 'Chichewa; Chewa; Nyanja', 'value': 'chiCheŵa, chinyanja' },
  { 'label': 'Chinese', 'value': '中文 (Zhōngwén), 汉语, 漢語' },
  { 'label': 'Chuvash', 'value': 'чӑваш чӗлхи' },
  { 'label': 'Cornish', 'value': 'Kernewek' },
  { 'label': 'Corsican', 'value': 'corsu, lingua corsa' },
  { 'label': 'Cree', 'value': 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { 'label': 'Croatian', 'value': 'hrvatski' },
  { 'label': 'Czech', 'value': 'česky, čeština' },
  { 'label': 'Danish', 'value': 'dansk' },
  { 'label': 'Divehi; Dhivehi; Maldivian;', 'value': 'ދިވެހި' },
  { 'label': 'Dutch', 'value': 'Nederlands, Vlaams' },
  { 'label': 'English', 'value': 'English' },
  { 'label': 'Esperanto', 'value': 'Esperanto' },
  { 'label': 'Estonian', 'value': 'eesti, eesti keel' },
  { 'label': 'Ewe', 'value': 'Eʋegbe' },
  { 'label': 'Faroese', 'value': 'føroyskt' },
  { 'label': 'Fijian', 'value': 'vosa Vakaviti' },
  { 'label': 'Finnish', 'value': 'suomi, suomen kieli' },
  { 'label': 'French', 'value': 'français, langue française' },
  { 'label': 'Fula; Fulah; Pulaar; Pular', 'value': 'Fulfulde, Pulaar, Pular' },
  { 'label': 'Galician', 'value': 'Galego' },
  { 'label': 'Georgian', 'value': 'ქართული' },
  { 'label': 'German', 'value': 'Deutsch' },
  { 'label': 'Greek, Modern', 'value': 'Ελληνικά' },
  { 'label': 'Guaraní', 'value': 'Avañeẽ' },
  { 'label': 'Gujarati', 'value': 'ગુજરાતી' },
  { 'label': 'Haitian; Haitian Creole', 'value': 'Kreyòl ayisyen' },
  { 'label': 'Hausa', 'value': 'Hausa, هَوُسَ' },
  { 'label': 'Hebrew (modern)', 'value': 'עברית' },
  { 'label': 'Herero', 'value': 'Otjiherero' },
  { 'label': 'Hindi', 'value': 'हिन्दी, हिंदी' },
  { 'label': 'Hiri Motu', 'value': 'Hiri Motu' },
  { 'label': 'Hungarian', 'value': 'Magyar' },
  { 'label': 'Interlingua', 'value': 'Interlingua' },
  { 'label': 'Indonesian', 'value': 'Bahasa Indonesia' },
  { 'label': 'Interlingue', 'value': 'Originally called Occidental; then Interlingue after WWII' },
  { 'label': 'Irish', 'value': 'Gaeilge' },
  { 'label': 'Igbo', 'value': 'Asụsụ Igbo' },
  { 'label': 'Inupiaq', 'value': 'Iñupiaq, Iñupiatun' },
  { 'label': 'Ido', 'value': 'Ido' },
  { 'label': 'Icelandic', 'value': 'Íslenska' },
  { 'label': 'Italian', 'value': 'Italiano' },
  { 'label': 'Inuktitut', 'value': 'ᐃᓄᒃᑎᑐᑦ' },
  { 'label': 'Japanese', 'value': '日本語 (にほんご／にっぽんご)' },
  { 'label': 'Javanese', 'value': 'basa Jawa' },
  { 'label': 'Kalaallisut, Greenlandic', 'value': 'kalaallisut, kalaallit oqaasii' },
  { 'label': 'Kannada', 'value': 'ಕನ್ನಡ' },
  { 'label': 'Kanuri', 'value': 'Kanuri' },
  { 'label': 'Kashmiri', 'value': 'कश्मीरी, كشميري‎' },
  { 'label': 'Kazakh', 'value': 'Қазақ тілі' },
  { 'label': 'Khmer', 'value': 'ភាសាខ្មែរ' },
  { 'label': 'Kikuyu, Gikuyu', 'value': 'Gĩkũyũ' },
  { 'label': 'Kinyarwanda', 'value': 'Ikinyarwanda' },
  { 'label': 'Kirghiz, Kyrgyz', 'value': 'кыргыз тили' },
  { 'label': 'Komi', 'value': 'коми кыв' },
  { 'label': 'Kongo', 'value': 'KiKongo' },
  { 'label': 'Korean', 'value': '한국어 (韓國語), 조선말 (朝鮮語)' },
  { 'label': 'Kurdish', 'value': 'Kurdî, كوردی‎' },
  { 'label': 'Kwanyama, Kuanyama', 'value': 'Kuanyama' },
  { 'label': 'Latin', 'value': 'latine, lingua latina' },
  { 'label': 'Luxembourgish, Letzeburgesch', 'value': 'Lëtzebuergesch' },
  { 'label': 'Luganda', 'value': 'Luganda' },
  { 'label': 'Limburgish, Limburgan, Limburger', 'value': 'Limburgs' },
  { 'label': 'Lingala', 'value': 'Lingála' },
  { 'label': 'Lao', 'value': 'ພາສາລາວ' },
  { 'label': 'Lithuanian', 'value': 'lietuvių kalba' },
  { 'label': 'Luba-Katanga', 'value': '' },
  { 'label': 'Latvian', 'value': 'latviešu valoda' },
  { 'label': 'Manx', 'value': 'Gaelg, Gailck' },
  { 'label': 'Macedonian', 'value': 'македонски јазик' },
  { 'label': 'Malagasy', 'value': 'Malagasy fiteny' },
  { 'label': 'Malay', 'value': 'bahasa Melayu, بهاس ملايو‎' },
  { 'label': 'Malayalam', 'value': 'മലയാളം' },
  { 'label': 'Maltese', 'value': 'Malti' },
  { 'label': 'Māori', 'value': 'te reo Māori' },
  { 'label': 'Marathi (Marāṭhī)', 'value': 'मराठी' },
  { 'label': 'Marshallese', 'value': 'Kajin M̧ajeļ' },
  { 'label': 'Mongolian', 'value': 'монгол' },
  { 'label': 'Nauru', 'value': 'Ekakairũ Naoero' },
  { 'label': 'Navajo, Navaho', 'value': 'Diné bizaad, Dinékʼehǰí' },
  { 'label': 'Norwegian Bokmål', 'value': 'Norsk bokmål' },
  { 'label': 'North Ndebele', 'value': 'isiNdebele' },
  { 'label': 'Nepali', 'value': 'नेपाली' },
  { 'label': 'Ndonga', 'value': 'Owambo' },
  { 'label': 'Norwegian Nynorsk', 'value': 'Norsk nynorsk' },
  { 'label': 'Norwegian', 'value': 'Norsk' },
  { 'label': 'Nuosu', 'value': 'ꆈꌠ꒿ Nuosuhxop' },
  { 'label': 'South Ndebele', 'value': 'isiNdebele' },
  { 'label': 'Occitan', 'value': 'Occitan' },
  { 'label': 'Ojibwe, Ojibwa', 'value': 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  { 'label': 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', 'value': 'ѩзыкъ словѣньскъ' },
  { 'label': 'Oromo', 'value': 'Afaan Oromoo' },
  { 'label': 'Oriya', 'value': 'ଓଡ଼ିଆ' },
  { 'label': 'Ossetian, Ossetic', 'value': 'ирон æвзаг' },
  { 'label': 'Panjabi, Punjabi', 'value': 'ਪੰਜਾਬੀ, پنجابی‎' },
  { 'label': 'Pāli', 'value': 'पाऴि' },
  { 'label': 'Persian', 'value': 'فارسی' },
  { 'label': 'Polish', 'value': 'polski' },
  { 'label': 'Pashto, Pushto', 'value': 'پښتو' },
  { 'label': 'Portuguese', 'value': 'Português' },
  { 'label': 'Quechua', 'value': 'Runa Simi, Kichwa' },
  { 'label': 'Romansh', 'value': 'rumantsch grischun' },
  { 'label': 'Kirundi', 'value': 'kiRundi' },
  { 'label': 'Romanian, Moldavian, Moldovan', 'value': 'română' },
  { 'label': 'Russian', 'value': 'русский язык' },
  { 'label': 'Sanskrit (Saṁskṛta)', 'value': 'संस्कृतम्' },
  { 'label': 'Sardinian', 'value': 'sardu' },
  { 'label': 'Sindhi', 'value': 'सिन्धी, سنڌي، سندھی‎' },
  { 'label': 'Northern Sami', 'value': 'Davvisámegiella' },
  { 'label': 'Samoan', 'value': 'gagana faa Samoa' },
  { 'label': 'Sango', 'value': 'yângâ tî sängö' },
  { 'label': 'Serbian', 'value': 'српски језик' },
  { 'label': 'Scottish Gaelic; Gaelic', 'value': 'Gàidhlig' },
  { 'label': 'Shona', 'value': 'chiShona' },
  { 'label': 'Sinhala, Sinhalese', 'value': 'සිංහල' },
  { 'label': 'Slovak', 'value': 'slovenčina' },
  { 'label': 'Slovene', 'value': 'slovenščina' },
  { 'label': 'Somali', 'value': 'Soomaaliga, af Soomaali' },
  { 'label': 'Southern Sotho', 'value': 'Sesotho' },
  { 'label': 'Spanish; Castilian', 'value': 'español, castellano' },
  { 'label': 'Sundanese', 'value': 'Basa Sunda' },
  { 'label': 'Swahili', 'value': 'Kiswahili' },
  { 'label': 'Swati', 'value': 'SiSwati' },
  { 'label': 'Swedish', 'value': 'svenska' },
  { 'label': 'Tamil', 'value': 'தமிழ்' },
  { 'label': 'Telugu', 'value': 'తెలుగు' },
  { 'label': 'Tajik', 'value': 'тоҷикӣ, toğikī, تاجیکی‎' },
  { 'label': 'Thai', 'value': 'ไทย' },
  { 'label': 'Tigrinya', 'value': 'ትግርኛ' },
  { 'label': 'Tibetan Standard, Tibetan, Central', 'value': 'བོད་ཡིག' },
  { 'label': 'Turkmen', 'value': 'Türkmen, Түркмен' },
  { 'label': 'Tagalog', 'value': 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔' },
  { 'label': 'Tswana', 'value': 'Setswana' },
  { 'label': 'Tonga (Tonga Islands)', 'value': 'faka Tonga' },
  { 'label': 'Turkish', 'value': 'Türkçe' },
  { 'label': 'Tsonga', 'value': 'Xitsonga' },
  { 'label': 'Tatar', 'value': 'татарча, tatarça, تاتارچا‎' },
  { 'label': 'Twi', 'value': 'Twi' },
  { 'label': 'Tahitian', 'value': 'Reo Tahiti' },
  { 'label': 'Uighur, Uyghur', 'value': 'Uyƣurqə, ئۇيغۇرچە‎' },
  { 'label': 'Ukrainian', 'value': 'українська' },
  { 'label': 'Urdu', 'value': 'اردو' },
  { 'label': 'Uzbek', 'value': 'zbek, Ўзбек, أۇزبېك‎' },
  { 'label': 'Venda', 'value': 'Tshivenḓa' },
  { 'label': 'Vietnamese', 'value': 'Tiếng Việt' },
  { 'label': 'Volapük', 'value': 'Volapük' },
  { 'label': 'Walloon', 'value': 'Walon' },
  { 'label': 'Welsh', 'value': 'Cymraeg' },
  { 'label': 'Wolof', 'value': 'Wollof' },
  { 'label': 'Western Frisian', 'value': 'Frysk' },
  { 'label': 'Xhosa', 'value': 'isiXhosa' },
  { 'label': 'Yiddish', 'value': 'ייִדיש' },
  { 'label': 'Yoruba', 'value': 'Yorùbá' },
  { 'label': 'Zhuang, Chuang', 'value': 'Saɯ cueŋƅ, Saw cuengh' },
];
